---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-8.6
  - name: debian-7.11
  - name: centos-6.8
  - name: centos-7.3
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      communicator: winrm
      shell_type: powershell
    provisioner:
      require_chef_omnibus: true

suites:
  - name: install_only
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::install_binary]
    excludes: ['windows-2012r2']
    attributes:
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    excludes: ['debian-8.2', 'centos-7.3', 'windows-2012r2']
    attributes:
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
  - name: source
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    excludes: ['windows-2012r2']
    attributes:
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        install_method: 'source'
        config:
          consul: '127.0.0.1:8500'
      go:
        version: '1.7.4'
  - name: runit
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    excludes: ['windows-2012r2']
    attributes:
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        init_style: 'runit'
        config:
          consul: '127.0.0.1:8500'
  - name: systemd
    run_list:
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    includes: ['debian-8.2', 'centos-7.3']
    attributes:
      consul:
        init_style: 'systemd'
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        init_style: 'systemd'
        config:
          consul: '127.0.0.1:8500'
  - name: windows
    run_list:
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config_win]
    includes: ['windows-2012r2']
    attributes:
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
  - name: supervisor
    run_list:
      - recipe[supervisor::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    includes: ['centos-7.3']
    attributes:
      consul:
        init_style: 'supervisor'
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        init_style: 'supervisor'
        config:
          consul: '127.0.0.1:8500'
