#!/bin/bash

set -e

version=$1
systems=( darwin_386 darwin_amd64 dragonfly_386 dragonfly_amd64 freebsd_386 freebsd_amd64 freebsd_arm linux_386 linux_amd64 linux_arm netbsd_386 netbsd_amd64 netbsd_arm openbsd_386 openbsd_amd64 plan9_386 solaris_amd64 windows_386 windows_amd64 )
files=()

function get_files {
  for system in "${systems[@]}"
  do
    file=("consul-template_${version}_${system}.tar.gz")
    files+=(${file})
  done
}

function print_checksums {
  echo Generating checksums for v${version}

  for file in "${files[@]}"
  do
    binary=https://github.com/hashicorp/consul-template/releases/download/v${version}/${file}
    checksum=$(curl -L -s $binary | shasum -a 256 | awk '{print $1}')
    echo $file: $checksum
  done
}

get_files
print_checksums
